dist: focal

language: python

python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
  - 3.13

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install .

script: python tests/test_pyxdl.py
